services:
  
  dynamodb:
    container_name: hackathon-dynamodb
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:latest
    ports:
      - "8000"
    volumes:
      - './dynamodb-local/data:/home/dynamodblocal/data'

  streamlit:
    container_name: hackathon-streamlit
    command: ['--server.runOnSave', 'true']
    build:
      dockerfile: Dockerfile
      target: streamlit
    ports:
      - "8501:8501"
    environment:
      APPLICATION: 'cornell-ai-hackathon-2025'
      AWS_ENDPOINT_URL_DYNAMODB: 'http://dynamodb:8000/'
      AWS_PROFILE: 'cornell-ai-hackathon-2025'
    volumes:
      - '$HOME/.aws:/home/streamlit/.aws'
      - './streamlit-app:/code'
      - './thisapp:/code/thisapp'
      - '${PWD}/.env:/code/.env'

  fastapi:
    container_name: hackathon-fastapi
    command: ['--reload']
    build:
      dockerfile: Dockerfile
      target: fastapi
    depends_on:
      - dynamodb
    ports:
      - "8000:8000"
    environment:
      APPLICATION: 'cornell-ai-hackathon-2025'
      AWS_PROFILE: 'cornell-ai-hackathon-2025'
    volumes:
      - '${HOME}/.aws:/root/.aws'
      - './fastapi-app:/code'
      - './thisapp:/code/thisapp'
      - '${PWD}/.env:/code/.env'

  devcontainer:
    container_name: hackathon-devcontainer
    build:
      dockerfile: Dockerfile
      target: devcontainer
    environment:
      APPLICATION: 'cornell-ai-hackathon-2025'
      AWS_ENDPOINT_URL_DYNAMODB: 'http://dynamodb:8000/'
      AWS_PROFILE: 'cornell-ai-hackathon-2025'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${HOME}/.aws:/root/.aws'
      - '.:/code'
      - '.:/workspace'
